import CityHeroSection from "@/app/locations/components/CityHeroSection";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import React from "react";

const cities = [
  "Bloomington",
  "Carmel",
  "Elkhart",
  "Evansville",
  "Fishers",
  "Fort Wayne",
  "Indianapolis",
  "Lafayette",
  "South Bend",
  "Terre Haute",
  "Alexandria",
  "Anderson",
  "Angola",
  "Attica",
  "Auburn",
  "Aurora",
  "Austin",
  "Avon",
  "Bargersville",
  "Batesville",
  "Bedford",
  "Beech Grove",
  "Berne",
  "Bicknell",
  "Bluffton",
  "Boonville",
  "Brazil",
  "Bremen",
  "Bright",
  "Brownsburg",
  "Brownstown",
  "Cambridge City",
  "Cedar Lake",
  "Chandler",
  "Charlestown",
  "Chesterton",
  "Cicero",
  "Clarksville",
  "Clinton",
  "Columbia City",
  "Columbus",
  "Connersville",
  "Corydon",
  "Country Squire Lakes",
  "Crawfordsville",
  "Crown Point",
  "Cumberland",
  "Danville",
  "De Motte",
  "Decatur",
  "Dunkirk",
  "Dunlap",
  "Dyer",
  "East Chicago",
  "Edinburgh",
  "Ellettsville",
  "Elwood",
  "Fort Branch",
  "Fortville",
  "Frankfort",
  "Franklin",
  "Garrett",
  "Gary",
  "Gas City",
  "Georgetown",
  "Goshen",
  "Granger",
  "Greencastle",
  "Greendale",
  "Greenfield",
  "Greensburg",
  "Greentown",
  "Greenwood",
  "Griffith",
  "Hammond",
  "Hanover",
  "Hartford City",
  "Hebron",
  "Heritage Lake",
  "Hidden Valley",
  "Highland",
  "Hobart",
  "Huntertown",
  "Huntingburg",
  "Huntington",
  "Jasper",
  "Jeffersonville",
  "Kendallville",
  "Knox",
  "Kokomo",
  "La Porte",
  "Lagrange",
  "Lake Station",
  "Lakes of the Four Seasons",
  "Lawrence",
  "Lawrenceburg",
  "Lebanon",
  "Leo - Cedarville",
  "Ligonier",
  "Linton",
  "Logansport",
  "Lowell",
  "Madison",
  "Marion",
  "Martinsville",
  "McCordsville",
  "Melody Hill",
  "Merrillville",
  "Michigan City",
  "Middlebury",
  "Mishawaka",
  "Mitchell",
  "Monticello",
  "Mooresville",
  "Mount Vernon",
  "Muncie",
  "Munster",
  "Nappanee",
  "New Albany",
  "New Carlisle",
  "New Castle",
  "New Haven",
  "New Whiteland",
  "Newburgh",
  "Noblesville",
  "North Manchester",
  "North Terre Haute",
  "North Vernon",
  "North Webster",
  "Notre Dame",
  "Ossian",
  "Paoli",
  "Pendleton",
  "Peru",
  "Pittsboro",
  "Plainfield",
  "Plymouth",
  "Portage",
  "Porter",
  "Portland",
  "Princeton",
  "Rensselaer",
  "Richmond",
  "Rochester",
  "Rockville",
  "Roselawn",
  "Rushville",
  "Salem",
  "Schererville",
  "Scottsburg",
  "Sellersburg",
  "Seymour",
  "Shelbyville",
  "Sheridan",
  "Simonton Lake",
  "Smithville - Sanders",
  "South Haven",
  "Speedway",
  "St.John",
  "Sullivan",
  "Syracuse",
  "Tell City",
  "Tipton",
  "Union City",
  "Upland",
  "Valparaiso",
  "Vincennes",
  "Wabash",
  "Walkerton",
  "Warsaw",
  "Washington",
  "West Lafayette",
  "Westfield",
  "Westville",
  "Whiteland",
  "Whitestown",
  "Whiting",
  "Winchester",
  "Winfield",
  "Winona Lake",
  "Yorktown",
  "Zionsville",
];

const description =
  "We provide home appliance repair and HVAC system services throughout all of the top cities in Indiana! Whether you're looking for expert appliance repair, need to have your HVAC system fixed, or simply scheduling a maintenance call, Sears Home Services has expert technicians in your city.";
export default function page() {
  return (
    <div>
      {/* <Link href={`${params.state}/anniston`}>{params.state}</Link> */}
      <CityHeroSection cities={cities} description={description} />
    </div>
  );
}
